language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - 'npm run test:ci'
env:
  global:
    - secure: >-
        pvg5IE+UeLCQ2b3bekUu1CdtzQQ3pizPJVbdjSlqQUVGrjdc2wmxdrxANADu8nYisRT6Mvj9XoGoPOm1rhv7WtBgioAQD4qScW7kPevqD85iXWT1VylvHMLQ3XzBuf+cvnbtp36vw6OK/rDFvVLyvTj7e4n0GYZ4lxXsndIwwmkQqd/al+H0GB6adOa5Xh1I9uBrwr44aoru2TdcRPciw6Kbqtpg09yHCr+zFd5zWjQVkqmaQDs5bYLaQopyvOBTkHRJ3MtDCIzC9TdDUhkb04ql+KuNkXnJRKL8Y1pq4qDZcpnUTR1M8BJPImA95u8wd+v9G//c8JKtzI55Ru+qwjNuoxSDoeuUwvJpRpDiUa6SIKpi5A2eOvV0HkwRrGFheBh44pOBnksEb5yzGb06RTV7pe5SXurOBZ4KD1PR2X8ID/nS4MV4L84WMXbow6c+1vLUf5luoJYIEFJ8fC9GPcHdfXnfCrEhYu4/5ZFne1ZpJ0/X+J5S/pjJqi3KYARv7+ORHbEiJBTV3LoY87mGPCgJKZR9cvBa6jyTTB8E+n5vtVsIeunEuXaguzeHSzFjQQa0G/ZdOhnnc4bIUhe6Ow/XhMmog6H57zorABMm72woEbCkCoaMdUTnGThN+hXa2d/MFdCmoMkpRdY+lLsNv/ENJbOfDv1ZFitF1RQwsMk=
