language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - 'npm run test:ci'
env:
  global:
    - secure: >-
        oX34G+BgKnamlJAdp4ffeZki6+9dFO2YRUanJl14JVIKs4zwYwxNWsMJqvWiW1nss0vOAnaelf2OR8u7lDgKC+iBQaX9k/glicyBer2y8bDlgTmxAsElOw7p17d1gSfdkpwBvbfOp8SEMoWoekIK0K//lSPJjWfVLAp4cYdNM7cW00X2F9KNlrGVl2552ufpwMwuGFDTt/2OFJGS8vO6ZNEvUxkAYExqLTQYczn8P5td7z4Vk/xV7W4/uZ96HRJcnp+YrwgLp/U/LEpmctXK28vsROycPkGc2zfxGQTU/GNCmlPBSmGZibVvAqZmtLPvGxtKP16BTpzyio6hSD+7rzelKNaOoIN5nNZWirZDkqsSuCCPRL+gSgIK0cSQfSzw72okvF3sTRjwZbHdT4xb7l43gQSD7nJJI9r9Pn0/60r0XXXoE0zSxlIYGWPimFbVvxxlpJmWmayoY5+qEoOZ2oekRtuMIg3+U8s8rECh3y8VWeWHbKjZ4bWBvYGiVs1z66U3zr81VPSKwUQZrbpg48Cz3qKYMtNqVvQXeXtg7ZR8cRe6LYKsurICQAhAduKKjqW+jnkc8Yq0X8kva353rjqIOdnXKtoYZRlh/bcnDfHNm/I/4ar8yl+xDqCPRvWVmF5V8329+UL7wdCv14EFh+QhLegmge0Wkmnbj3luNlk=
